### ISSUE TITLE
Could you provide the files in the label_space folder

### ISSUE THREAD

**Issue by Lancelot365** [xingyizhou/UniDet#1]
Hi Xingyi,

Thanks for you wonderful and easy to use work! I have managed to do some testing with the models and they performed quite well.

However I am not able to find the files under label_spaces folder to train, e.g., datasets/label_spaces/learned_mAP+M.json
Could you provide those?

Also as a suggestion, maybe you can put the model_zoo in the main read_me. They are quite hard to find at a glance.

Thanks

* Links to the relevant documentation/comment:

**Comment by xingyizhou** [comment]
Hi,
  Thank you for your interest in our project. Both are great suggestions! I have uploaded the label spaces under `datasets/label_spaces/` (sorry they were ignored by .gitignore before) and updated the readme. Thanks!

Best,
Xingyi

**Comment by Lancelot365** [comment]
Thanks Xingyi!
